# Generated by Django 4.2.1 on 2023-05-22 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.CharField(choices=[('Chinese', 'CHINESE'), ('Italian', 'ITALIAN'), ('Turkish', 'TURKISH'), ('Mexican', 'MEXICAN'), ('Fast Food', 'FAST FOOD'), ('Vegan', 'VEGAN')], max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Metrics.cuisine')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('rate', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Metrics.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Metrics.cuisine')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Metrics.restaurant')),
            ],
        ),
    ]
