# Generated by Django 4.2.1 on 2023-05-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Metrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='cuisine',
            field=models.CharField(choices=[('Chinese', 'CHINESE'), ('Italian', 'ITALIAN'), ('Turkish', 'TURKISH'), ('Mexican', 'MEXICAN'), ('Fast Food', 'FAST FOOD'), ('Vegan', 'VEGAN')], max_length=75),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(choices=[('Chinese', 'CHINESE'), ('Italian', 'ITALIAN'), ('Turkish', 'TURKISH'), ('Mexican', 'MEXICAN'), ('Fast Food', 'FAST FOOD'), ('Vegan', 'VEGAN')], max_length=75),
        ),
        migrations.DeleteModel(
            name='Cuisine',
        ),
    ]
