# Generated by Django 4.2.1 on 2023-06-09 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Metrics', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewmeal',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='reviewrestaurant',
            name='rate',
        ),
    ]
