# Generated by Django 4.2.1 on 2023-06-09 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Metrics', '0007_remove_reviewmeal_rate_remove_reviewrestaurant_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrestaurant',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
